---
- name: install the elasticsearch
  become: yes
  hosts: efk
  roles:
    - { role: elasticsearch, es_instance_name: "node1" }

- name: install the kibana
  become: yes
  hosts: efk
  roles:
    - kibana

- name: install the td-agent(fluentd agent)
  become: yes
  hosts: efk
  roles:
    - td-agent
