---
- name: install apt-related binaries for Ansible c work
  apt: name={{ item }}  state=present update_cache=yes
  with_items:
    - python-software-properties
    - apt-transport-https

- name: add APT signing key for td-agent
  apt_key: url=https://packages.treasuredata.com/GPG-KEY-td-agent state=present

- name: add td-agent repository
  apt_repository: repo='deb https://packages.treasuredata.com/3/{{ ansible_distribution|lower }}/{{ ansible_distribution_release|lower }}/ {{ ansible_distribution_release|lower }} contrib' state=present

- name: install td-agent (when td_agent_version is not defined)
  apt: name=td-agent  update_cache=yes  state=present force=yes
  when: td_agent_version is not defined

- name: install td-agent (when td_agent_version is defined)
  apt: name="td-agent={{ td_agent_version }}*"  update_cache=yes  state=present force=yes
  when: td_agent_version is defined

- name: install libcurl and make for compiling plugins
  apt: name={{ item }}  state=present update_cache=yes
  with_items:
    - libcurl4-gnutls-dev
    - build-essential
  when: td_agent_plugins is defined or td_agent_plugins_versions is defined

- name: set INIT status and start
  service: name=td-agent state=started enabled=yes

- name: install plugins with specified versions, if any
  gem:
    name: "{{ item.value.name }}"
    executable: /opt/td-agent/embedded/bin/fluent-gem
    state: present
    version: "{{ item.value.version }}"
    user_install: no
  with_dict: "{{ td_agent_plugins_versions | default({}) }}"
  notify:
    - restart td-agent