---
- name: download and unarchive tomcat for pinpoint web
  unarchive:
    extra_opts: ['--strip-components=1', '--show-stored-names']
    src: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.6/bin/apache-tomcat-9.0.6.tar.gz
    dest: "{{ pinpoint_web_tomcat_home }}"
    remote_src: yes
    owner: "{{ pinpoint_user }}"
    group: "{{ pinpoint_group }}"

- name: deleted defaut webapps directories for pinpoint web
  file:
    path: "{{ pinpoint_web_tomcat_home }}/webapps/"
    state: "{{ item }}"
    owner: "{{ pinpoint_user }}"
    group: "{{ pinpoint_group }}"
  with_items:
    - absent
    - directory

- name: config tomcat logging path for pinpoint web
  template:
    src:  pinpoint-web/logging.properties.j2
    dest: "{{ pinpoint_web_tomcat_home }}/conf/logging.properties"
    mode: 0600

- name: config tomcat server.xml for pinpoint web
  template:
    src:  pinpoint-web/server.xml.j2
    dest: "{{ pinpoint_web_tomcat_home }}/conf/server.xml"
    mode: 0600