---
- name: create pinpoint-web working directories
  file:
    path: "{{ pinpoint_web_tomcat_home }}/webapps/ROOT"
    state: "{{ item }}"
    owner: "{{ pinpoint_user }}"
    group: "{{ pinpoint_group }}"
  with_items:
    - absent
    - directory

- name: download and unarchive pinpoint-web.war
  unarchive:
    src: pinpoint-web-1.7.1.war
    dest: "{{ pinpoint_web_tomcat_home }}/webapps/ROOT"
    setype: war
    owner: "{{ pinpoint_user }}"
    group: "{{ pinpoint_group }}"

- name: add pinpoint-web.service
  template:
    src:  pinpoint-web/pinpoint-web.service.j2
    dest: /etc/systemd/system/pinpoint-web.service
    mode: 0644
    owner: root
    group: root
  notify: "start pinpoint-web"


